ssh_keys:
     public: /tmp/go-ssh.pub
     private: /tmp/go-ssh

stack:
   vars:
      PROD_MODE: 1
      stage_dir: /home/ubuntu/stage_dir
      apache_proxy_image: geneontology/apache-proxy:v5
      S3_CRED_FILE: /tmp/go-aws-credentials
      S3_BUCKET: REPLACE_ME_APACHE_LOG_BUCKET

      # APACHE PROXY WILL ALLOW FOR HTTPS. Recommended for PRODUCTION
      USE_SSL: 1 
      S3_SSL_CERTS_LOCATION: s3://REPLACE_ME/geneontology.org.tar.gz

      # APACHE PROXY USE QOS module. Recommended for PRODUCTION
      USE_QOS: 1
      QS_ClientEventBlockCount: 350
      QS_ClientEventBlockCountSeconds: 100
      QS_ClientEventBlockExcludeIP: "9.9.9.9"

      gocam_solr_host: REPLACE_ME
      gocam_solr_tag: 0.2.0 # docker image version for the gocam-solr code itself.
   scripts: [ "stage.yaml", "start_services.yaml" ]
