- hosts: all
  vars_files:
  - vars.yaml
  - docker-vars.yaml
  - s3-vars.yaml
  - ssl-vars.yaml
  - qos-vars.yaml

  tasks:
  - name: Create stage directories
    file:
      path: '{{ stage_dir }}/{{ item }}'
      state: directory
    with_items:
      - conf
      - httpd-confs
      - credentials

  - name: Handle production mode ...
    block:
      - name: install production config from templates directory
        template:
          src: '{{ item.file }}'
          dest: '{{ stage_dir }}/{{ item.dir }}'
        with_items:
          - { file: 'docker-compose-production.yaml', dir: 'docker-compose.yaml' }
          - { file: 'config.yaml', dir: 'conf' }

      - name: install http conf file
        template:
          src: httpd-vhosts-prod-fastapi.conf 
          dest: '{{ stage_dir }}/httpd-confs/httpd-vhosts-prod-fastapi.conf'
        when: not REDIRECT_HTTP | bool

      - name: install http redirect file
        template:
          src: httpd-vhosts-prod-fastapi-redirect.conf 
          dest: '{{ stage_dir }}/httpd-confs/httpd-vhosts-prod-fastapi.conf'
        when: REDIRECT_HTTP | bool

      - name: install ssl configs from templates directory
        template:
          src: '{{ item.file }}'
          dest: '{{ stage_dir }}/{{ item.dir }}'
        with_items:
          - { file: 'httpd-vhosts-prod-fastapi-ssl.conf', dir: 'httpd-confs' }
        when: USE_SSL | bool

      - name: install qos config from templates directory
        template:
          src: qos.conf
          dest: '{{ stage_dir }}/qos.conf'
        when: USE_QOS | bool

      - name: copy s3cfg
        copy:
          src: "{{ S3_CRED_FILE }}"
          dest: "{{ stage_dir }}/credentials/s3cfg"

      - name: copy noop qos.conf 
        copy:
          src: "files/qos-noop.conf"
          dest: '{{ stage_dir }}/qos.conf'
        when: not USE_QOS | bool

      - name: copy robots.txt 
        copy:
          src: "files/robots.txt"
          dest: "{{ stage_dir }}/robots.txt"
    when: PROD_MODE | bool
