version: '3.7'
services:

  fastapi:
    hostname: gocam_solr
    container_name: gocam_solr
    volumes:
      - {{ stage_dir }}/conf/config.yaml:/code/app/conf/config.yaml
    image: 'geneontology/gocam-solr:{{ gocam_solr_tag }}'
    init: true
    restart: unless-stopped
    healthcheck:
      test: curl http://gocam_solr:8983 || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s

  apache_proxy:
    hostname: apache_gocam_solr
    container_name: apache_gocam_solr
    image: {{ apache_proxy_image }}
    volumes:
      - {{ stage_dir }}/httpd-confs:/etc/apache2/sites-enabled
      - {{ stage_dir }}/qos.conf:/etc/apache2/mods-enabled/qos.conf
      - {{ stage_dir }}/robots.txt:/var/www/html/robots.txt
      - {{ stage_dir }}/apache_logs:/var/log/apache2
      - {{ stage_dir }}/credentials:/opt/credentials
      - {{ stage_dir }}/credentials/s3cfg:/root/.aws/config
    ports:
      - "83:83"
      - "443:443"
      - "8983:8983"
    environment:
      - S3_PATH={{ S3_PATH }}/fastapi
      - S3_BUCKET={{ S3_BUCKET }}
      - USE_SSL={{ USE_SSL }}
      - S3_SSL_CERTS_LOCATION={{ S3_SSL_CERTS_LOCATION }}
      - USE_CLOUDFLARE={{ USE_CLOUDFLARE }}
    init: true
    restart: unless-stopped
    depends_on:
      - gocam_solr

